import { Prisma } from "@prisma/client";
import prisma from "@/lib/prisma";
import { invalidate } from "@/lib/cache";
import { route, HttpError } from "@/lib/api/handler";

interface MealItem {
  besinName: string;
  miktar: string;
  birim: string;
}

interface MealSample {
  name: string;
  items: MealItem[];
}

interface MealPattern {
  name: string;
  items: MealItem[];
  count: number;
  score: number;
  normalizedMealKey?: string;
}

export const POST = route({
  cors: true,
  auth: "dietitian",
  scope: "presets.auto-generate",
  handler: async ({ auth }) => {
    const diets = await prisma.diet.findMany({
      where: { dietitianId: auth.user!.id },
      take: 30,
      orderBy: { createdAt: "desc" },
      include: {
        oguns: {
          include: { items: { include: { besin: true, birim: true } } },
        },
      },
    });

    if (diets.length < 5) {
      throw new HttpError(
        "bad_request",
        "En az 5 diyet gerekli. Daha fazla diyet yazın.",
      );
    }

    const mealGroups: Record<string, MealSample[]> = {};
    for (const diet of diets) {
      for (const ogun of diet.oguns) {
        const normalizedName = normalizeMealName(ogun.name);
        if (!mealGroups[normalizedName]) mealGroups[normalizedName] = [];

        const mealItems = ogun.items
          .map((item) => ({
            besinName: item.besin?.name || "",
            miktar: item.miktar || "",
            birim: item.birim?.name || "",
          }))
          .filter((item) => item.besinName);

        if (mealItems.length > 0) {
          mealGroups[normalizedName].push({ name: ogun.name, items: mealItems });
        }
      }
    }

    const detectedPatterns: MealPattern[] = [];
    for (const [normalizedMealKey, meals] of Object.entries(mealGroups)) {
      if (meals.length < 3) continue;
      const patterns = findSimilarPatterns(meals, normalizedMealKey);
      for (const pattern of patterns) {
        pattern.normalizedMealKey = normalizedMealKey;
      }
      detectedPatterns.push(...patterns);
    }

    const createdPresets: Prisma.MealPresetGetPayload<{
      include: { items: true };
    }>[] = [];

    for (const pattern of detectedPatterns) {
      if (pattern.score < 60) continue;

      const normalizedMealKey = pattern.normalizedMealKey || "diğer";
      const mealType = getMealTypeCategory(normalizedMealKey);

      const existing = await prisma.mealPreset.findFirst({
        where: { name: pattern.name, isAutoGenerated: true },
      });

      if (existing) {
        await prisma.mealPreset.update({
          where: { id: existing.id },
          data: { patternScore: pattern.score, mealType },
        });
      } else {
        const preset = await prisma.mealPreset.create({
          data: {
            name: pattern.name,
            mealType,
            isAutoGenerated: true,
            patternScore: pattern.score,
            isActive: true,
            dietitianId: auth.user!.id,
            items: {
              create: pattern.items.map((item, idx) => ({
                besinName: item.besinName,
                miktar: item.miktar,
                birim: item.birim,
                order: idx,
              })),
            },
          },
          include: { items: true },
        });
        createdPresets.push(preset);
      }
    }

    if (createdPresets.length > 0) {
      invalidate.presets(auth.user!.id);
    }

    return {
      message: `${createdPresets.length} yeni preset oluşturuldu`,
      presets: createdPresets,
      patternsDetected: detectedPatterns.length,
    };
  },
});

function normalizeMealName(name: string): string {
  const lower = name.toLowerCase().trim();
  if (lower.includes("uyanınca") || lower.includes("uyaninca")) return "uyanınca";
  if (lower.includes("kahvaltı")) return "kahvaltı";
  if (lower.includes("öğle") || lower.includes("öğlen")) return "öğle";
  if (lower.includes("akşam")) return "akşam";
  if (lower.includes("ara")) return "ara_öğün";
  return "diğer";
}

function getMealTypeCategory(normalizedMealKey: string): string {
  if (normalizedMealKey === "uyanınca") return "uyaninca";
  if (normalizedMealKey === "kahvaltı") return "kahvalti";
  if (normalizedMealKey === "öğle") return "ogle";
  if (normalizedMealKey === "akşam") return "aksam";
  if (normalizedMealKey === "ara_öğün") return "ara_ogun";
  return "diger";
}

function findSimilarPatterns(meals: MealSample[], mealType: string): MealPattern[] {
  const patterns: MealPattern[] = [];

  for (let i = 0; i < meals.length; i++) {
    let similarCount = 0;
    const baseMeal = meals[i];

    for (let j = 0; j < meals.length; j++) {
      if (i === j) continue;
      const similarity = calculateMealSimilarity(baseMeal.items, meals[j].items);
      if (similarity >= 0.7) similarCount++;
    }

    const score = (similarCount / meals.length) * 100;
    if (score >= 60) {
      patterns.push({
        name: `Sık Kullanılan ${capitalize(mealType)}`,
        items: baseMeal.items,
        count: similarCount + 1,
        score: Math.round(score),
      });
      break;
    }
  }

  return patterns;
}

function calculateMealSimilarity(items1: MealItem[], items2: MealItem[]): number {
  if (items1.length === 0 || items2.length === 0) return 0;
  let matchCount = 0;
  for (const item1 of items1) {
    const match = items2.find(
      (item2) =>
        item2.besinName.toLowerCase() === item1.besinName.toLowerCase() &&
        item2.miktar === item1.miktar &&
        item2.birim === item1.birim,
    );
    if (match) matchCount++;
  }
  const totalItems = Math.max(items1.length, items2.length);
  return matchCount / totalItems;
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}
