import prisma from "@/lib/prisma";
import { getCachedPresets, invalidate } from "@/lib/cache";
import { route } from "@/lib/api/handler";
import { ok } from "@/lib/api/response";
import { CreatePresetInput } from "@/schemas/api/preset";

export const GET = route({
  cors: true,
  auth: "dietitian",
  scope: "presets.list",
  handler: async ({ request, auth }) => {
    const mealType = request.nextUrl.searchParams.get("mealType");
    return getCachedPresets(auth.user!.id, mealType);
  },
});

export const POST = route({
  cors: true,
  auth: "dietitian",
  schema: CreatePresetInput,
  scope: "presets.create",
  handler: async ({ body, auth }) => {
    const preset = await prisma.mealPreset.create({
      data: {
        name: body.name.trim(),
        mealType: body.mealType ?? null,
        isAutoGenerated: false,
        isActive: true,
        dietitianId: auth.user!.id,
        items: {
          create: body.items.map((item, idx) => ({
            besinName: item.besinName ?? item.besin ?? "",
            miktar: item.miktar,
            birim: item.birim,
            order: idx,
          })),
        },
      },
      include: { items: true },
    });
    invalidate.presets(auth.user!.id);
    return ok(preset, { status: 201 });
  },
});
